# Version Docker Compose
version: '3.8'

services:

  # Configuração MySql version
  mysql:
    # Imagem a ser baixada
    image: mysql:8.0.28
    # Nome do container
    container_name: mysql
    # Configuracao da porta de conexao
    ports:
      - 3306:3306
    environment:
      # Usuario da aplicacao
      MYSQL_USER: vendas
      MYSQL_PASSWORD: vendas
      # Usuario root
      MYSQL_ROOT_PASSWORD: root
      # Nome do banco de dados
      MYSQL_DATABASE: vendas_db

  # Configuração Jaeger - Monitoramento da aplicacao
  # rastreamento para aplicacoes microservico
  jaeger:
    # Imagem jaeger
    image: jaegertracing/all-in-one:1.31
    # Nome do container
    container_name: jaeger
    # Postas Configuradas
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

  # Configuração Prometheus Projeto
  # Obtenção de métricas no projeto de forma visual
  prometheus:
    # Imagem Prometheus
    image: prom/prometheus:v2.34.0-rc.2
    # Nome do container
    container_name: prometheus
    # Postas Configuradas
    ports: 
      - 9090:9090
    # Volume do container  
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # Executa um comando na criação do container  
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
